/**
\page p_sample_graphs Samples (in test)


Generated by <code>make doc</code> with https://www.graphviz.org/

\todo Autogenerate this page !

<table>

<tr>
<th>Sample graph</th>
<th>Source</th>
<th>Processed</th>
</tr>

<tr>
<th>graph_0</th>
<td>\image html graph_0_0_neato.svg</td>
<td>\image html graph_0_color_1_neato.svg</td>
</tr>


<tr>
<th>graph_1</th>
<td>\image html graph_1_0_neato.svg</td>
<td>\image html graph_1_color_1_neato.svg</td>
</tr>

<tr>
<th>graph_2</th>
<td>\image html graph_2_0_neato.svg</td>
<td>\image html graph_2_color_1_neato.svg</td>
</tr>

<tr>
<th>graph_3</th>
<td>\image html graph_3_0_neato.svg</td>
<td>\image html graph_3_color_1_neato.svg</td>
</tr>

<tr>
<th>graph_4</th>
<td>\image html graph_4_0_neato.svg</td>
<td>\image html graph_4_color_1_neato.svg</td>
</tr>

<tr>
<th>graph_41</th>
<td>\image html graph_41_0_neato.svg</td>
<td>\image html graph_41_color_1_neato.svg</td>
</tr>

<tr>
<th>graph_7</th>
<td>\image html graph_7_0_dot.svg</td>
<td>\image html graph_7_color_1_dot.svg</td>
</tr>

<tr>
<th>graph_9</th>
<td>\image html graph_9_0_neato.svg</td>
<td>\image html graph_9_color_1_neato.svg</td>
</tr>

<tr>
<th>graph_10</th>
<td>\image html graph_10_0_neato.svg</td>
<td>\image html graph_10_color_1_neato.svg</td>
</tr>

<tr>
<th>graph_Petersen</th>
<td><img style="width:100%;" src="graph_Petersen_0_neato.svg"> </td>
<td><img style="width:100%;" src="graph_Petersen_color_1_neato.svg"> </td>
</tr>

</table>
*/

