/**
\page p_sample_graphs Samples (in test)


Generated by <code>make doc</code> with https://www.graphviz.org/

<table>

<tr>
<th>Sample graph</th>
<th>Source</th>
<th>Processed</th>
</tr>

<tr>
<th>graph_0</th>
<td>\image html graph_0_0_neato.svg</td>
<td>\image html graph_0_color_1_neato.svg</td>
</tr>


<tr>
<th>graph_1</th>
<td>\image html graph_1_0_neato.svg</td>
<td>\image html graph_1_color_1_neato.svg</td>
</tr>

<tr>
<th>graph_2</th>
<td>\image html graph_2_0_neato.svg</td>
<td>\image html graph_2_color_1_neato.svg</td>
</tr>

<tr>
<th>graph_3</th>
<td>\image html graph_3_0_neato.svg</td>
<td>\image html graph_3_color_1_neato.svg</td>
</tr>

<tr>
<th>graph_4</th>
<td>\image html graph_4_0_neato.svg</td>
<td>\image html graph_4_color_1_neato.svg</td>
</tr>

<tr>
<th>graph_41</th>
<td>\image html graph_41_0_dot.svg</td>
<td>\image html graph_41_color_1_dot.svg</td>
</tr>

</table>
*/

