name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: skramm/debian_boost

    steps:
    - uses: actions/checkout@v3
    - name: install tools
      run: apt-get update; apt-get -y install build-essential libboost-all-dev
    - name: check version
      run: gcc --version; clang --version; cat /usr/include/boost/version.hpp | grep BOOST_LIB_VERSION
    - name: make1
      run: make
    - name: clean
      run: make clean
    - name: make2
      run: make CXX=clang++
