name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: skramm/debian_boost

    steps:
    - uses: actions/checkout@v3
    - name: install tools
      run: apt-get update; apt-get -y install clang build-essential libboost-all-dev

    - name: check version gcc
      run: gcc --version
    - name: check version clang
      run: clang --version;
    - name: check boost version
      run: cat /usr/include/boost/version.hpp | grep BOOST_LIB_VERSION

    - name: make1
      run: make
    - name: clean
      run: make clean
    - name: make2
      run: make CXX=clang++
