# basic testing with Microsoft compiler
# uses this: https://github.com/TheMrMilchmann/setup-msvc-dev

# trying this
# https://github.com/marketplace/actions/engineerd-configurator
# but unclear how to mode the headers to a location wherre MSVC will find them

name: CI-testing-msvc

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  job3:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup MSVC Developer Command Prompt
        uses: TheMrMilchmann/setup-msvc-dev@v2.0.0
        with:
          arch: x64
      - name: get boost
        run: wget https://github.com/boostorg/graph/archive/refs/tags/boost-1.82.0.zip

      - name: run msvc
        run: cl /EHsc demo/sample_1.cpp

