# basic testing with Microsoft compiler
# uses this: https://github.com/TheMrMilchmann/setup-msvc-dev

name: CI-testing-msvc

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  job3:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup MSVC Developer Command Prompt
        uses: TheMrMilchmann/setup-msvc-dev@v2.0.0
        with:
          arch: x64
      - run: cd
      - run: dir
      - name: get boost
        run: curl https://github.com/boostorg/graph/archive/refs/tags/boost-1.82.0.zip
      - run: dir
      - name: unzip boost
        run: unzip boost-1.82.0.zip
      - name: run msvc
        run: cl /EHsc demo/sample_1.cpp

